import { inheritableDict } from "./inheritableDict.js"

export const wordDict = [{ word: "hanitae",
    definition: ["a hunter", "Hunter's title"],
    root: "h-n-t",
    prefix: "none",
    rootLength: 3,
    animate: true,
    type: "noun",
    aliases: ["hanta"],
    legalVTypes: inheritableDict[0].legalVTypes,
    legalAlters: inheritableDict[0].legalAlters,
    temporalTense: inheritableDict[0].temporalTense,
    nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
    bannedTense: inheritableDict[0].bannedTense,
    args: inheritableDict[0].args
    },
    { word: "sattokubi",
        definition: ["arsonist", "Artificer's alias"],
        root: "s-t-k",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["satto"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "mabkan",
        definition: ["wallflower; an asocial person", "Watcher's given name"],
        root: "m-b-k",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["banolnak yopwa", "banno"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "masinabi",
        definition: ["messenger; delivery person", "Spearmaster's title"],
        root: "m-s-n",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["akita"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "pajmuy",
        definition: ["that which is convinced most often", "Monk's given name"],
        root: "j-m-y",
        prefix: "passive",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["sahini mayabi", "maya"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "pachmigae",
        definition: ["that which is hidden", "Survivor's given name"],
        root: "ch-m-g",
        prefix: "passive",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["ommuy", "omi"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "tonun",
        definition: ["that which tells stories the most", "Gourmand's given name"],
        root: "t-n-n",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["makikanae", "maki"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "lamlan",
        definition: ["a stream", "Rivulet's nickname"],
        root: "l-l-n",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["yanginaeja lamlan", "lani"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "sapinae",
        definition: ["a saint; devout adherent to religious beliefs, particularly beliefs that espouse asceticism", "Saint's title"],
        root: "s-p-n",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["saen"],
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "dang",
        definition: ["a woman"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "ong",
        definition: ["a man"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "lam",
        definition: ["a gender neutral or third gender person"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "taw",
        definition: ["1st person pronoun; I, me"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: {
        vocative: [-1],
        genitive: true,
        subject: [0, 1, 2, 3, 4, 4.1, 4.2, 5, 6, 7, 8, 9, 10],
        timing: [-1],
        locative: [2, 3, 4, 4.1, 4.2, 5, 6, 7, 8, 9, 10],
        ablative: [3, 8],
        instrumental: [3, 4, 4.1, 4.2, 5, 7, 8, 10],
        indirobj: [3, 4, 4.1, 4.2, 5, 7, 8, 10],
        destination: [3],
        dirobj: [7, 8, 9]
}
    },
    { word: "no",
        definition: ["2nd person pronoun; you"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "tawhoy",
        definition: ["1st person plural; we, us", "literally taw and the group marker 'hoy' combined"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: {
            vocative: [-1],
            genitive: true,
            subject: [0, 1, 2, 3, 4, 4.1, 4.2, 5, 6, 7, 8, 9, 10],
            timing: [-1],
            locative: [2, 3, 4, 4.1, 4.2, 5, 6, 7, 8, 9, 10],
            ablative: [3, 8],
            instrumental: [3, 4, 4.1, 4.2, 5, 7, 8, 10],
            indirobj: [3, 4, 4.1, 4.2, 5, 7, 8, 10],
            destination: [3],
            dirobj: [7, 8, 9]
        }
    },
    { word: "nohoy",
        definition: ["2nd person plural; you all", "literally no and the group marker 'hoy' combined"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "hoy",
        definition: ["an address or measure word for groups of people; used to pluralise pronouns"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: false,
        type: "noun",
        legalVTypes: [-1],
        legalAlters: ["none"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: {
            vocative: [-1],
            genitive: false,
            subject: [-1],
            timing: [-1],
            locative: [-1],
            ablative: [-1],
            instrumental: [-1],
            indirobj: [-1],
            destination: [-1],
            dirobj: [-1]
        }
    },
    { word: "molongjae",
        definition: ["Scavenger; the Scavengers' endonym adapted into yongasabi"],
        root: "m-l-ng-j",
        prefix: "none",
        rootLength: 4,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "yongasabi",
        definition: ["slugcat", "the slugcat people; the endonym for slugcats, literally 'wandering people'", "the slugcat language"],
        root: "y-ng-s",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[0].legalVTypes,
        legalAlters: inheritableDict[0].legalAlters,
        temporalTense: inheritableDict[0].temporalTense,
        nonTemporalTenses: inheritableDict[0].nonTemporalTenses,
        bannedTense: inheritableDict[0].bannedTense,
        args: inheritableDict[0].args
    },
    { word: "gila",
        definition: ["a lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "jin",
        definition: ["lizard; sometimes used to refer to longer-bodied lizards, limbless lizards, or snakes, but is often used interchangeably with gila"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "mayae gila",
        definition: ["green lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        aliases: ["jogga gila"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "paeh gila",
        definition: ["pink lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        alises: ["sojil gila"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "monna gila",
        definition: ["blue lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "naw gila",
        definition: ["salamander"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        aliases: ["lolanibi"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "dowwim gila",
        definition: ["caramel lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        aliases: ["chalae"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "kotuw",
        definition: ["cyan lizard"],
        root: "k-t-w",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["kotaw gila", "sayin gila"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "sei gila",
        definition: ["red lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        aliases: ["koddim gila", "isobi"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "kawla gila",
        definition: ["yellow lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        aliases: ["boyya gila"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "wuy gila",
        definition: ["black lizard"],
        root: "g-l",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "heichmug",
        definition: ["white lizard"],
        root: "ch-m-g",
        prefix: "reflexive",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["yoyila gila"],
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "sinawabi",
        definition: ["eel lizard"],
        root: "s-n-w",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[1].legalVTypes,
        legalAlters: inheritableDict[1].legalAlters,
        temporalTense: inheritableDict[1].temporalTense,
        nonTemporalTenses: inheritableDict[1].nonTemporalTenses,
        bannedTense: inheritableDict[1].bannedTense,
        args: inheritableDict[1].args
    },
    { word: "jalman",
        definition: ["batfly"],
        root: "j-l-m",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "nonei",
        definition: ["eggbug"],
        root: "n-n",
        prefix: "none",
        rootLength: 4,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "japchei suy",
        definition: ["noodlefly"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "toka suy",
        definition: ["lantern mouse"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "kojei",
        definition: ["centipede"],
        root: "k-j",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "pusit",
        definition: ["squidcada"],
        root: "p-s-t",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "mochnolabi",
        definition: ["hazer"],
        root: "ch-n-l",
        prefix: "dative",
        rootLength: 3,
        animate: true,
        type: "noun",
        aliases: ["mochi"],
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "heichu",
        definition: ["snail"],
        root: "ch",
        prefix: "reflexive",
        rootLength: 1,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "tuw",
        definition: ["yeek"],
        root: "t-w",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[6].legalVTypes,
        legalAlters: inheritableDict[6].legalAlters,
        temporalTense: inheritableDict[6].temporalTense,
        nonTemporalTenses: inheritableDict[6].nonTemporalTenses,
        bannedTense: inheritableDict[6].bannedTense,
        args: inheritableDict[6].args
    },
    { word: "bol",
        definition: ["meat"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[7].legalVTypes,
        legalAlters: inheritableDict[7].legalAlters,
        temporalTense: inheritableDict[7].temporalTense,
        nonTemporalTenses: inheritableDict[7].nonTemporalTenses,
        bannedTense: inheritableDict[7].bannedTense,
        args: inheritableDict[7].args
    },
    { word: "mun",
        definition: ["a fruit; any fruit, not just blue fruit"],
        root: "m-n",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[7].legalVTypes,
        legalAlters: inheritableDict[7].legalAlters,
        temporalTense: inheritableDict[7].temporalTense,
        nonTemporalTenses: inheritableDict[7].nonTemporalTenses,
        bannedTense: inheritableDict[7].bannedTense,
        args: inheritableDict[7].args
    },
    { word: "gulay",
        definition: ["a vegetable"],
        root: "g-l-y",
        prefix: "none",
        rootLength: 3,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[7].legalVTypes,
        legalAlters: inheritableDict[7].legalAlters,
        temporalTense: inheritableDict[7].temporalTense,
        nonTemporalTenses: inheritableDict[7].nonTemporalTenses,
        bannedTense: inheritableDict[7].bannedTense,
        args: inheritableDict[7].args
    },
    { word: "meiki",
        definition: ["a meal"],
        root: "m-k",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[7].legalVTypes,
        legalAlters: inheritableDict[7].legalAlters,
        temporalTense: inheritableDict[7].temporalTense,
        nonTemporalTenses: inheritableDict[7].nonTemporalTenses,
        bannedTense: inheritableDict[7].bannedTense,
        args: inheritableDict[7].args
    },
    { word: "mok",
        definition: ["food"],
        root: "m-k",
        prefix: "none",
        rootLength: 2,
        animate: true,
        type: "noun",
        legalVTypes: inheritableDict[7].legalVTypes,
        legalAlters: inheritableDict[7].legalAlters,
        temporalTense: inheritableDict[7].temporalTense,
        nonTemporalTenses: inheritableDict[7].nonTemporalTenses,
        bannedTense: inheritableDict[7].bannedTense,
        args: inheritableDict[7].args
    },
{ word: "koddim",
    definition: ["red"],
    root: "k-d-m",
    prefix: "none",
    rootLength: 3,
    animate: false,
    animateReq: false,
    type: "adj",
    legalVTypes: inheritableDict[2].legalVTypes,
    legalAlters: inheritableDict[2].legalAlters,
    temporalTense: inheritableDict[2].temporalTense,
    nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
    bannedTense: inheritableDict[2].bannedTense,
    args: inheritableDict[2].args
    },
    { word: "nonija",
        definition: ["orage"],
        root: "n-j",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "boyya",
        definition: ["yellow"],
        root: "b-y",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jogga",
        definition: ["green"],
        root: "j-g",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "monna",
        definition: ["blue"],
        root: "m-n",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "sayin",
        definition: ["cyan"],
        root: "s-y-n",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "chanju",
        definition: ["purple"],
        root: "ch-n-j",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "sojil",
        definition: ["pink"],
        root: "s-j-l",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "daw",
        definition: ["black"],
        root: "d-w",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "dowwim",
        definition: ["brown"],
        root: "d-w-m",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "lobba",
        definition: ["grey"],
        root: "l-b",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "yoyila",
        definition: ["white"],
        root: "y-y-l",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "lin",
        definition: ["fast"],
        root: "l-n",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "molla",
        definition: ["big"],
        root: "m-l",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "kamuy",
        definition: ["small"],
        root: "k-m-y",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jeipcho",
        definition: ["long; tall"],
        root: "j-p-ch",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jeili",
        definition: ["short"],
        root: "j-l",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jolla",
        definition: ["short"],
        root: "j-l",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "chuhogol",
        definition: ["temperate; mild in temperature"],
        root: "ch-h",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "chah",
        definition: ["warm, hot; any non-cold temperature"],
        root: "ch-h",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "cheihi",
        definition: ["lukewarm, tepid; mild heat"],
        root: "ch-h",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "chohei",
        definition: ["hot; sweltering; dangerously or uncomfortably warm"],
        root: "ch-h",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "samuy",
        definition: ["chilly, cold; any temperature that is not warm or mild"],
        root: "s-m-y",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "samyei",
        definition: ["freezing; dangerously cold"],
        root: "s-m-y",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "seimyo",
        definition: ["cool; mildly or uncomfortably cold"],
        root: "s-m-y",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jommiy",
        definition: ["confident"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "yojommiy",
        definition: ["unconfident"],
        root: "static",
        prefix: "negative",
        rootLength: 0,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "heismih",
        definition: ["indulgent"],
        root: "s-m-h",
        prefix: "reflexive",
        rootLength: 3,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "omi",
        definition: ["lucky; fortunate"],
        root: "m",
        prefix: "middle",
        rootLength: 1,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "paen",
        definition: ["prosperous"],
        root: "p-n",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "ipon",
        definition: ["auspicious"],
        root: "p-n",
        prefix: "causative",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "isaeja",
        definition: ["killer; lethal, deadly"],
        root: "s",
        prefix: "causative",
        rootLength: 1,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "isaegol",
        definition: ["killer; murderous"],
        root: "s",
        prefix: "causative",
        rootLength: 1,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "kataeja",
        definition: ["cutting; sharp"],
        root: "k-t",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "jamiyae",
        definition: ["convincing; persuasive"],
        root: "j-m-y",
        prefix: "none",
        rootLength: 3,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "mae",
        definition: ["good"],
        root: "m",
        prefix: "none",
        rootLength: 1,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "kobba",
        definition: ["bad"],
        root: "k-b",
        prefix: "none",
        rootLength: 2,
        animate: false,
        animateReq: false,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "akija",
        definition: ["evil"],
        root: "k",
        prefix: "none",
        rootLength: 1,
        animate: false,
        animateReq: true,
        type: "adj",
        legalVTypes: inheritableDict[2].legalVTypes,
        legalAlters: inheritableDict[2].legalAlters,
        temporalTense: inheritableDict[2].temporalTense,
        nonTemporalTenses: inheritableDict[2].nonTemporalTenses,
        bannedTense: inheritableDict[2].bannedTense,
        args: inheritableDict[2].args
    },
    { word: "takwon",
    definition: ["morning"],
    root: "t-k-w-n",
    prefix: "none",
    rootLength: 4,
    animate: false,
    type: "noun",
    legalVTypes: inheritableDict[3].legalVTypes,
    legalAlters: inheritableDict[3].legalAlters,
    temporalTense: "any",
    nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
    },
    { word: "chomug",
        definition: ["night"],
        root: "ch-m-g",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
    },
    { word: "nakolka",
        definition: ["sunrise"],
        root: "n-k",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
        },
    { word: "takipalo",
        definition: ["sunset"],
        root: "none",
        prefix: "none",
        rootLength: 0,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
    },
    { word: "ochdaw",
        definition: ["nightfall"],
        root: "ch-d-w",
        prefix: "middle",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
        },
    { word: "kamasda",
        definition: ["today; this cycle"],
        root: "m-s-d",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
        },
    { word: "kayuni",
        definition: ["today; this day"],
        root: "y-n",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[3].legalVTypes,
        legalAlters: inheritableDict[3].legalAlters,
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        args: inheritableDict[3].args
        },
    { word: "ma",
        definition: ["question particle"],
        root: "none",
        prefix: "none",
        rootLength: 0,
        animate: false,
        type: "sentence-final particle",
        legalVTypes: [0, 1, 2, 3, 4, 4.1, 4.2, 5, 6, 7, 8, 9, 10],
        legalAlters: ["none"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "imperative",
        joinWith: " ", // joinWith is a post-verb alteration property
        // some postVAlters need to be suffixed directly to the verb, like tto
        // some need a space, like ma
        // so we write down which it is
        args: {
            vocative: [-1],
            genitive: [-1],
            subject: [-1],
            timing: [-1],
            locative: [-1],
            ablative: [-1],
            instrumental: [-1],
            indirobj: [-1],
            destination: [-1],
            dirobj: [-1]
        }},
    { word: "akita",
        definition: ["a spear"],
        root: "k-t",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "katae",
        definition: ["a machete"],
        root: "k-t",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "masin",
        definition: ["a message"],
        root: "m-s-n",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "angchi",
        definition: ["a text, inscription, book, or scroll"],
        root: "ng-ch",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "teiba",
        definition: ["a plant"],
        root: "t-b",
        prefix: "none",
        rootLength: 4,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "ping",
        definition: ["a bottle"],
        root: "p-ng",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "sadi",
        definition: ["things that can be used to bind; cord, thread, rope", "wire"],
        root: "s-d",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "isod",
        definition: ["thread; fine string appropriate for sewing"],
        root: "s-d",
        prefix: "causative",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "masin",
        definition: ["a message"],
        root: "m-s-n",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "baenang",
        definition: ["a bag"],
        root: "b-n-ng",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "sangja",
        definition: ["a box"],
        root: "s-ng-j",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[4].legalVTypes,
        legalAlters: inheritableDict[4].legalAlters,
        temporalTense: inheritableDict[4].temporalTense,
        nonTemporalTenses: inheritableDict[4].nonTemporalTenses,
        bannedTense: inheritableDict[4].bannedTense,
        args: inheritableDict[4].args
    },
    { word: "kip",
        definition: ["a shelter"],
        root: "k-p",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "yangsei",
        definition: ["migratory path"],
        root: "y-ng-s",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "hanoltak",
        definition: ["hunting grounds"],
        root: "h-n-t",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "solani",
        definition: ["shoreline; shore"],
        root: "s-l-n",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "mimashu",
        definition: ["ocean, sea"],
        root: "m-sh",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "pukong",
        definition: ["city"],
        root: "p-k-ng",
        prefix: "none",
        rootLength: 3,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-dependent"],
        args: inheritableDict[8].args
    },
    { word: "bak",
        definition: ["outside"],
        root: "static",
        prefix: "none",
        rootLength: 0,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "cho",
        definition: ["inside"],
        root: "ch",
        prefix: "none",
        rootLength: 1,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "tuh",
        definition: ["around; indicates movement or position around or surrounding something", "perimeter, circumference"],
        root: "t-h",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "seing",
        definition: ["across; a crossing"],
        root: "s-ng",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "hago",
        definition: ["along; the length of"],
        root: "h-g",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "osam",
        definition: ["range; area; territory", "around, as in the range or space that an action takes place"],
        root: "s-m",
        prefix: "middle",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "lago",
        definition: ["passing; while passing by"],
        root: "l-g",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "akto",
        definition: ["through; going through"],
        root: "k-t",
        prefix: "none",
        rootLength: 2,
        animate: false,
        type: "noun",
        legalVTypes: inheritableDict[8].legalVTypes,
        legalAlters: inheritableDict[8].legalAlters,
        temporalTense: inheritableDict[8].temporalTense,
        nonTemporalTenses: inheritableDict[8].nonTemporalTenses,
        bannedTense: inheritableDict[8].bannedTense,
        compoundTypes: [0], // position word phrase
        compoundPart: ["0-head"],
        args: inheritableDict[8].args
    },
    { word: "lamya",
    definition: ["to return (somewhere)"],
    root: "l-m-y",
    rootLength: 3,
    prefix: "none",
    animate: true,
    type: "verb",
    legalVTypes: [-1],
    verbType: [3],
    legalAlters: ["adverb"],
    temporalTense: "any",
    nonTemporalTenses: true,
        bannedTense: "none",
    dirobjThem: true,
    args: {
        vocative: true,
        genitive: false,
        subject: true,
        timing: true,
        locative: true,
        ablative: true,
        instrumental: true,
        indirobj: true,
        destination: true,
        dirobj: true
    }},
    { word: "lana",
        definition: ["to move fast; to rush from one place to another"],
        root: "l-n",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [3],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: true,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: true,
            instrumental: true,
            indirobj: true,
            destination: true,
            dirobj: true
        }},
    { word: "maya",
        definition: ["to walk"],
        root: "m-y",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [3],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: true,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: true,
            instrumental: true,
            indirobj: true,
            destination: true,
            dirobj: true
        }},
    { word: "hanta",
        definition: ["to hunt"],
        root: "h-n-t",
        rootLength: 3,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [4],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }},
    { word: "satka",
        definition: ["to burn"],
        root: "s-t-k",
        rootLength: 3,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [4],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }},
    { word: "maka",
        definition: ["to eat"],
        root: "m-k",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [4.1],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }},

    { word: "aktodaka",
        definition: ["to spear"],
        root: "k-t",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [4.2],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    {word: "kapa",
        definition: ["to rest", "to shelter", "to lie still in one place"],
        root: "k-p",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [5],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: false
        }},
    { word: "asa",
        definition: ["to die"],
        root: "s",
        rootLength: 1,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [6],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: false,
            destination: false,
            dirobj: false
        }
    },
    { word: "jamya",
        definition: ["to convince; to reason with"],
        root: "j-m-y",
        rootLength: 3,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [7],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    { word: "kadma",
        definition: ["to embarrass; to fluster"],
        root: "k-d-m",
        rootLength: 3,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [7],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    { word: "nana",
        definition: ["to look at; to see"],
        root: "n-n",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [8],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: true,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    { word: "aba",
        definition: ["to hit; to whack; to impact"],
        root: "b",
        rootLength: 1,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [9],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    { word: "paha",
        definition: ["to hold; to grasp"],
        root: "p-h",
        rootLength: 2,
        prefix: "none",
        animate: true,
        type: "verb",
        legalVTypes: [-1],
        verbType: [10],
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: true,
            indirobj: true,
            destination: false,
            dirobj: true
        }
    },
    { word: "angsa",
        definition: ["to be; to exist"],
        root: "'-ng-s",
        prefix: "none",
        rootLength: "irregular",
        animate: false,
        type: "verb",
        legalVTypes: [-1],
        verbType: [0], // desc angsa
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: false,
            locative: false,
            ablative: false,
            instrumental: false,
            indirobj: false,
            destination: false,
            dirobj: true
        }},
    { word: "angsa",
        definition: ["to be; to exist"],
        root: "'-ng-s",
        prefix: "none",
        rootLength: "irregular",
        animate: false,
        type: "verb",
        legalVTypes: [-1],
        verbType: [1], // poss angsa
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: false,
            locative: false,
            ablative: false,
            instrumental: false,
            indirobj: false,
            destination: false,
            dirobj: true
        }
    },
    { word: "angsa",
        definition: ["to be; to exist"],
        root: "'-ng-s",
        prefix: "none",
        rootLength: "irregular",
        animate: false,
        type: "verb",
        legalVTypes: [-1],
        verbType: [2], // loc angsa
        legalAlters: ["adverb"],
        temporalTense: "any",
        nonTemporalTenses: true,
        bannedTense: "none",
        dirobjThem: false,
        args: {
            vocative: true,
            genitive: false,
            subject: true,
            timing: true,
            locative: true,
            ablative: false,
            instrumental: false,
            indirobj: false,
            destination: false,
            dirobj: false
        }
    }
    // this is a really stupid band-aid solution
    // i'd like to update these to not be true/false but instead to use an array of verbTypes
    // but i'll do that later
    ]